### ISSUE TITLE
[REPORT]: SCUS_975.58 Jak and Daxter: The Lost Frontier

### ISSUE THREAD

**Issue by INDRAPhilip** [ps2homebrew/Open-PS2-Loader-Compatibility-list#101]
### Checks

- [X] I have checked if a report of the same game, in the same test environment, is already included
- [x] I have tested all features from the feature list before making this report

### gameplay

Working

### Console model

SCPH-39001

### OPL version / revision

OPL 1.2.0 beta 1901

### title

Jak and Daxter: The Lost Frontier

### Game Region code (ID)

SCUS_975.58

### device used on test

USB

### format

ISO

### media

DVD5

### features

- [X] VMC
- [X] IGR
- [ ] PADEMU
- [X] GSM

### comments about this report

with shutter in iso for FMVs

**Comment by israpps** [comment]
Please test all functionalities so we can accept this report

**Comment by INDRAPhilip** [comment]
Of course I don't have a DS3 controller to test PADEMU in some game, but the Jak and Daxter game series has a problem with PADEMU
