### ISSUE TITLE
[REPORT]: Midnight Club 3: Dub Edition Remix

### ISSUE THREAD

**Issue by INDRAPhilip** [ps2homebrew/Open-PS2-Loader-Compatibility-list#102]
### Checks

- [X] I have checked if a report of the same game, in the same test environment, is already included
- [X] I have tested all features from the feature list before making this report

### gameplay

Working

### Console model

SCPH-39001

### OPL version / revision

OPL 1.2.0 beta 1901

### title

Midnight Club 3: Dub Edition Remix

### Game Region code (ID)

SLUS_213.55

### device used on test

USB

### format

ISO

### media

DVD9

### features

- [x] VMC
- [X] IGR
- [X] PADEMU
- [X] GSM

### comments about this report

In zso the intro and FMV scenes stutter, some construction cracks during the game, otherwise it works perfectly and in iso the intros don't stutter, however the FMV scenes stutter and even more in the .ul test on the exfat device. In previous versions of opl vmc ends up corrupting, vmc can still occur on smb and usb as before, but in my tests on usb so far nothing happens, anything is better not to use.

**Comment by israpps** [comment]
VMC is not working?



I´m just confirming before merging

**Comment by INDRAPhilip** [comment]
> A VMC não está funcionando?

Yes, it's for now before it corrupted the VMC very often on eth and usb in old versions of 0.9.3 and 0.9.4, but as far as I've played I haven't had this problem in beta 1.2.0 on usb, but that could be that It still happens at some point in the game I just couldn't test it.

**Comment by INDRAPhilip** [comment]
Or it could be that the issue with VMC has been fixed in the new betas

**Comment by INDRAPhilip** [comment]
> > VMC is not working??
> 
> Yes, it's for now before it corrupted the VMC very often on eth and usb in old versions of 0.9.3 and 0.9.4, but as far as I've played I haven't had this problem in beta 1.2.0 on usb, but that could be that It still happens at some point in the game I just couldn't test it.
