### ISSUE TITLE
[REPORT]: Prince of Persia The Two Thrones

### ISSUE THREAD

**Issue by INDRAPhilip** [ps2homebrew/Open-PS2-Loader-Compatibility-list#105]
### Checks

- [X] I have checked if a report of the same game, in the same test environment, is already included
- [X] I have tested all features from the feature list before making this report

### gameplay

Working

### Console model

SCPH-39001

### OPL version / revision

OPL 1.2.0 beta 1901

### title

Prince of Persia The Two Thrones

### Game Region code (ID)

SLUS_212.87 

### device used on test

USB

### format

ISO

### media

DVD5

### features

- [X] VMC
- [X] IGR
- [X] PADEMU
- [X] GSM

### comments about this report

there is no shuttering in cutscenes in iso and zso

**Comment by INDRAPhilip** [comment]
The iso tested I rebuilt it with Dkz Studio because the iso was more than 4gb and when I rebuilt it it went to a little, but 1gb.

**Comment by AKuHAK** [comment]
rebuilt isos are not accepted cause you change lba

**Comment by AKuHAK** [comment]
I hope thi is the only iso you rebuild?

**Comment by INDRAPhilip** [comment]
> I hope thi is the only iso you rebuild?

Yes, this was the only one I rebuilt, because I had verified that it would be possible to change the lba to more than 4GB to complete the DVD size, unlike what happens with other games that have dummy files to improve reading or complete the DVD size!

**Comment by INDRAPhilip** [comment]
But can I rephrase the question with the game with 4GB if that's the problem right?

**Comment by AKuHAK** [comment]
It is known that compatibility is changed a lot when iso is rebuilt, so only vanilla iso game, which md5 matches redump.org are accepted

**Comment by AKuHAK** [comment]
Its not a problem. You can install over 4gb games on exfat formatted flash. Or install it with usbutil in ul iso format

**Comment by INDRAPhilip** [comment]
> It is known that compatibility is changed a lot when iso is rebuilt, so only vanilla iso game, which md5 matches redump.org are accepted

I have no problem with it, I can test that way, but if the game is 4GB plus lba is 1GB, the cutscenes will be more drastic as you will have to read more data that doesn't exist to not have the white screen problems with the dummy files it was a common error in the iso and this can be fixed by removing them or rebuilding the iso even though it's not the problem of this game

**Comment by INDRAPhilip** [comment]
> rebuilt



> Its not a problem. You can install over 4gb games on exfat formatted flash. Or install it with usbutil in ul iso format

I know that and I can do it this way, possibly it won't change anything from the slightly more than 1GB version that reconstructed at most the cutscenes crashing a little more
