### ISSUE TITLE
[REPORT]: SLUS_209.98 Dragon Ball Z: Budokai 3

### ISSUE THREAD

**Issue by INDRAPhilip** [ps2homebrew/Open-PS2-Loader-Compatibility-list#97]
### Checks

- [X] I have checked if a report of the same game, in the same test environment, is already included
- [x] I have tested all features from the feature list before making this report

### gameplay

Working

### Console model

SCPH-39001

### OPL version / revision

1.1.0, OPL 1.2.0 beta 1901

### title

Dragon Ball Z: Budokai 3

### Game Region code (ID)

SLUS_209.98

### device used on test

USB

### format

ISO

### media

DVD5

### features

- [X] VMC
- [X] IGR
- [x] PADEMU
- [X] GSM

### comments about this report

with shutter on zso and iso on FMV

**Comment by israpps** [comment]
Please confirm all of the listed functionalities
